### ISSUE TITLE
Media library not scanning

### ISSUE THREAD

**Issue by phorward** [DaveMDS/epymc#17] opened 2016-09-21 20:04 UTC
Hello again,

this is another issue I have when I tried to use epymc on the Arch Linux ARM device. There is a USB hard drive connected, I can access all its files using the command-line or even other programs. But when I give it as music source to epymc, nothing happens, except 3 songs are loaded? I cannot be a rights problem! Surely the amount of files is very high. The connected device is an ext4 device. Is there any possibility to trace or debug why nothing happens here?

Cheers!

**Comment by phorward** [comment] 2016-09-21 21:32
Hello, I found the reason. Its a bug in the music.py, I'm checking out if I can fix it by myself.

**Comment by phorward** [comment] 2016-09-22 07:21
Hey folks, I now checked it out, but was unable to fix the bug.

This is the traceback that occurs:

Traceback (most recent call last):
  File "efl/ecore/efl.ecore.pyx", line 341, in efl.ecore._ecore_task_cb (efl/ecore/efl.ecore.c:3308)
  File "efl/ecore/efl.ecore_idler.pxi", line 77, in efl.ecore.Idler._task_exec (efl/ecore/efl.ecore.c:9356)
  File "efl/ecore/efl.ecore_idler.pxi", line 78, in efl.ecore.Idler._task_exec (efl/ecore/efl.ecore.c:9305)
  File "/usr/lib/python3.5/site-packages/epymc/plugins/music/music.py", line 356, in rebuild_db_idler
    if self._songs_db.id_exists('file://' + full_path):
  File "/usr/lib/python3.5/site-packages/epymc/sdb.py", line 122, in id_exists
    return key in self._sh
  File "/usr/lib/python3.5/shelve.py", line 102, in __contains__
    return key.encode(self.keyencoding) in self.dict
UnicodeEncodeError: 'utf-8' codec can't encode character '\udcf3' in position 69: surrogates not allowed

The problem is, that os.listdir() returns a filename from my media library that is "/tmp/Taraxacum/Rainmaker/Taraxacum - 12 - Lo Que Faltó.mp3": The "ó" is converted by os.listdir() to a UTF-8 representation. I tried several fixes to handle it, but my knowledge is too less on Python's string encodings and the file system behavior, maybe you have a quicker solution?

**Comment by phorward** [comment] 2016-09-22 10:04
Hello, I started a pull request, got a working version right now at my local box (I use the epymc package from arch linux aur)

**Comment by DaveMDS** [comment] 2016-09-28 05:53
Hi, thanks for reporting!
I'm not really sure the pull request is the best way to fix the issue, we shouldn't handle the encoding in sdb.py... but I need to dig a bit more on this issue. Will do in the next few days

**Comment by phorward** [comment] 2016-09-28 05:57
Yeah, I really was not sure if this would be the best way, but it was a way to get it work for me. Indeed, handling these encoding errors with Python is annoying.

**Comment by DaveMDS** [comment] 2016-09-28 17:20
I'm not able to reproduce your issue :/
I tried with a file named "Test File àèìòùó asd asd.mp3", in my local harddisk, in an ntfs share and in a fat32 usb key.
EpyMC always scanned the file correctly (using python 3.5 like your)

I can think at 2 different problems:
1. your mp3 file is strange (can you send it to me? maybe via email)
2. your system locale is not well configured, please paste here the output of the `locale` command.

**Comment by DaveMDS** [comment] 2017-08-16 20:00
well, no more activitiy, I'm closing this. 
Please reopen if it still occur

**Closed by DaveMDS** 2017-08-16 20:00 UTC
